### create-client
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

### create-client-account
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "97d526b4-cf3c-4e50-9457-a073f5ad2916"
}

### create-transaction
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "34d4d2ca-ac3e-4b49-b85f-a012d6ef1e78",
    "account_id_to": "0e8be345-2428-4fdd-80af-935685b34c98",
    "amount": 50
}